{{- if .Values.frontendLegacy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "signalen.frontend-legacy.fullname" . }}
  labels:
    {{- include "signalen.frontend-legacy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "signalen.frontend-legacy.selectorLabels" . | nindent 4 }}
{{- end }}
