{{- if .Values.frontendWcag.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "signalen.frontend-wcag.fullname" . }}
  labels:
    {{- include "signalen.frontend-wcag.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "signalen.frontend-wcag.selectorLabels" . | nindent 4 }}
{{- end }}
