{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "signalen.backend-celery-beat.fullname" . }}
  labels:
    {{- include "signalen.backend-celery-beat.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "signalen.backend-celery-beat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/backend/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "signalen.backend-celery-beat.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "signalen.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend-celery-beat
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "signalen.backend.fullname" . }}
            - secretRef:
                name: {{ include "signalen.backend.fullname" . }}
          command: ["/usr/local/bin/celery"]
          args:
            - '--app=signals'
            - 'beat'
            - '--loglevel=info'
            - '--pidfile=/tmp/celerybeat.pid'
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            - name: media
              mountPath: /media
            - name: dwh-media
              mountPath: /dwh_media
      volumes:
        - name: media
        {{- if eq .Values.storage.backend "pvc" }}
          persistentVolumeClaim:
            claimName: {{ include "signalen.backend.fullname" . }}-media
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: dwh-media
        {{- if eq .Values.storage.backend "pvc" }}
          persistentVolumeClaim:
            claimName: {{ include "signalen.backend.fullname" . }}-datawarehouse
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}